# Site settings
title: Werur's Blog             # 你的博客网站标题
SEOTitle: Werur's Blog			# 在后面会详细谈到
description: "If you can't explain it simply, you don't understand it well enough"    # 随便说点，描述一下

# SNS settings      
github_username: fishmanlol     # 你的github账号
weibo_username: N/A      # 你的微博账号，底部链接会自动更新的。

# Build settings
highlighter: rouge
permalink: pretty
paginate: 10

# Sidebar settings
sidebar: true  #添加侧边栏
sidebar-about-description: "Like coffee, esppcially Geisha"
sidebar-avatar: /img/avatar-me.png     #你的大头贴，请使用绝对地址.

# Featured Tags
featured-tags: true  
featured-condition-size: 0 

disqus_username: werur_me
comments: true

# Google Analytics
ga_track_id: 'UA-118334394-1'            # 你用Google账号去注册一个就会给你一个这样的id
ga_domain: werur.me			# 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto。

header-img: img/home-bg.jpg

gems: [jekyll-paginate, jekyll-admin]

markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  
url: "http://werur.me" # your host, for absolute URL
baseurl: ""   
